import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import { ThemeProvider } from "next-themes";
import "./globals.css";
import AuthWrapper from "@/providers/auth-provider";
import { ClientWrapper } from "./_components/client-wrapper";

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${poppins.variable} font-poppins antialiased`}>
        <AuthWrapper >
          <ClientWrapper>
            <ThemeProvider attribute="class" defaultTheme="light" >
              {children}
            </ThemeProvider>
          </ClientWrapper>
        </AuthWrapper>
      </body>
    </html>
  );
}
